apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-store-deployment
  labels:
    app: file-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-store
  template:
    metadata:
      labels:
        app: file-store
    spec:
      containers:
      - name: file-store
        image: file-store:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/tmp/text"
          name: file-store-pv-storage
      volumes:
      - name: file-store-pv-storage
        persistentVolumeClaim:
          claimName: file-store-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: file-store-service
spec:
  selector:
    app: file-store
  ports:
    - protocol: TCP
      port: 82
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-store-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi