apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-invoke-deployment
  labels:
    app: api-invoke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-invoke
  template:
    metadata:
      labels:
        app: api-invoke
    spec:
      containers:
      - name: api-invoke
        image: api-invoke:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-invoke-service
spec:
  selector:
    app: api-invoke
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8080
  type: LoadBalancer